// ============================================================
//  Worship Metrics Dashboard — Data File
//  Christ Lincoln — Worship Ministries
//
//  This file is the ONLY file the refresh pipeline edits.
//  The HTML dashboard loads it via <script src> and renders from it.
//
//  Structure:
//    DASHBOARD_DATA.lastRefreshed  — date string for display
//    DASHBOARD_DATA.quarters       — ordered quarter labels
//    DASHBOARD_DATA.spaces         — per-space quarterly arrays
//    DASHBOARD_DATA.weeklyData     — keyed by quarter label
//
//  Generated by refresh-dashboard.py. Do not hand-edit; changes will be
//  overwritten on the next refresh.  To close a quarter or adjust rules,
//  edit pco-mcp/dashboard_config.py.
// ============================================================

const DASHBOARD_DATA = {
    lastRefreshed: '2026-10-07',
    quarters: ['Q1 23-24', 'Q2 23-24', 'Q3 23-24', 'Q4 23-24', 'Q1 24-25', 'Q2 24-25', 'Q3 24-25', 'Q4 24-25', 'Q1 25-26', 'Q2 25-26', 'Q3 25-26', 'Q4 25-26', 'Q1 26-27', 'Q2 26-27'],
    spaces: {
        sanctuary: {
            weeklyAvg: [586, 582, 657, 559, 602, 610, 621, 622, 590, 611, 663, 659, 618, 757],
            service8am: [194, 191, 248, 213, 207, 218, 222, 218, 203, 237, 221, 228, 211, 238],
            service930am: [219, 226, 237, 227, 238, 242, 231, 260, 249, 240, 283, 259, 252, 288],
            service11am: [142, 135, 138, 119, 130, 128, 146, 144, 138, 134, 159, 164, 155, 231],
            firstTimeGuests: [88, 86, null, null, 118, 155, 152, 231, 229, 607, 508, 398, null, null],
            infantBaptisms: [34, 30, 34, 25, 27, 22, 22, null, 4, 8, 5, 9, null, null],
            childBaptisms: [null, null, null, null, 0, 1, 0, 1, null, 1, 1, 1, null, null],
            adultBaptisms: [null, null, null, null, 7, 7, 4, 6, null, 0, 0, 1, null, null],
            streamingHours: [null, null, null, null, null, null, null, null, 778, 1141, 1262, 1074, 987, 72],
            serviceEaster: [null, null, null, null, null, null, null, null, null, null, null, 8, null, null]
        },
        sumner: {
            weeklyAvg: [705, 718, 775, 640, 726, 722, 788, 742, 748, 747, 787, 843, 660, 785],
            service930am: [435, 426, 465, 405, 458, 453, 474, 449, 465, 453, 463, 502, 384, 508],
            service11am: [270, 292, 310, 235, 268, 269, 314, 293, 283, 294, 324, 305, 276, 277],
            firstTimeGuests: [null, 155, null, null, 222, 365, 412, 269, 344, 485, 545, 572, null, null],
            infantBaptisms: [null, null, null, null, 7, 10, 5, 3, 5, 5, 9, 14, null, null],
            childBaptisms: [null, null, null, null, 1, 2, 2, 1, 2, 3, 3, 0, null, null],
            adultBaptisms: [null, null, null, null, 0, 2, 0, 1, null, 0, 0, 3, null, null],
            streamingHours: [null, null, null, null, null, null, null, null, 890, 1284, 1526, 1429, 1285, 52],
            serviceEaster: [null, null, null, null, null, null, null, null, null, null, null, 36, null, null]
        },
        yh: {
            weeklyAvg: [491, 503, 566, 519, 514, 553, 569, 627, 633, 672, 603, 660, 645, null],
            service9am: [249, 249, 270, 286, 273, 301, 285, 356, 320, 331, 292, 360, 343, null],
            service1030am: [242, 254, 296, 233, 241, 252, 284, 271, 313, 341, 311, 289, 302, null],
            firstTimeGuests: [null, 4, null, null, 157, 369, 213, 258, 292, 589, 275, 418, null, null],
            infantBaptisms: [null, null, null, null, 1, 4, 8, 5, 7, 9, 7, 3, null, null],
            childBaptisms: [null, null, null, null, 0, 3, 0, 4, null, 8, 2, 4, null, null],
            adultBaptisms: [null, null, null, null, 3, 1, 1, 1, null, 3, 0, 0, null, null],
            streamingHours: [null, null, null, null, null, null, null, null, 689, 737, 830, 808, 642, 53],
            serviceEaster: [null, null, null, null, null, null, null, null, null, null, null, 11, null, null]
        }
    },
    weeklyData: {
        'Q3 25-26': {
            attendance: [
                { date: '2026-01-04', sanctuary: 711, sumner: 791, yh: 612 },
                { date: '2026-01-11', sanctuary: 689, sumner: 822, yh: 618 },
                { date: '2026-01-18', sanctuary: 599, sumner: 817, yh: 584 },
                { date: '2026-01-25', sanctuary: 719, sumner: 565, yh: 517 },
                { date: '2026-02-01', sanctuary: 605, sumner: 793, yh: 629 },
                { date: '2026-02-08', sanctuary: 658, sumner: 830, yh: 620 },
                { date: '2026-02-15', sanctuary: 629, sumner: 768, yh: 589 },
                { date: '2026-02-22', sanctuary: 649, sumner: 840, yh: 599 },
                { date: '2026-03-01', sanctuary: 642, sumner: 845, yh: 679 },
                { date: '2026-03-08', sanctuary: 576, sumner: 746, yh: 475 },
                { date: '2026-03-15', sanctuary: 659, sumner: 649, yh: 549 },
                { date: '2026-03-22', sanctuary: 639, sumner: 827, yh: 590 },
                { date: '2026-03-29', sanctuary: 840, sumner: 939, yh: 778 }
            ],
            streaming: [
                { date: '2026-01-04', sanctuary: 4633, sumner: 6900, yh: 4798 },
                { date: '2026-01-11', sanctuary: 5049, sumner: 6369, yh: 2865 },
                { date: '2026-01-18', sanctuary: 5947, sumner: 6102, yh: 3557 },
                { date: '2026-01-25', sanctuary: 8700, sumner: 7754, yh: 5192 },
                { date: '2026-02-01', sanctuary: 6364, sumner: 8096, yh: 4353 },
                { date: '2026-02-08', sanctuary: 4680, sumner: 1711, yh: 4030 },
                { date: '2026-02-15', sanctuary: 4776, sumner: 6660, yh: 2924 },
                { date: '2026-02-18', label: 'Ash Wednesday', sanctuary: 1316, sumner: 0, yh: 0 },
                { date: '2026-02-19', label: 'Ash Wednesday', sanctuary: 0, sumner: 1955, yh: 1375 },
                { date: '2026-02-22', sanctuary: 6185, sumner: 7415, yh: 4320 },
                { date: '2026-03-01', sanctuary: 5583, sumner: 5565, yh: 3907 },
                { date: '2026-03-04', sanctuary: 856, sumner: 0, yh: 0 },
                { date: '2026-03-08', sanctuary: 4208, sumner: 4766, yh: 3391 },
                { date: '2026-03-11', sanctuary: 701, sumner: 0, yh: 0 },
                { date: '2026-03-15', sanctuary: 6589, sumner: 7937, yh: 3405 },
                { date: '2026-03-18', sanctuary: 810, sumner: 0, yh: 0 },
                { date: '2026-03-22', sanctuary: 4843, sumner: 14704, yh: 2716 },
                { date: '2026-03-25', sanctuary: 528, sumner: 0, yh: 0 },
                { date: '2026-03-29', sanctuary: 4172, sumner: 6024, yh: 2999 }
            ]
        },
        'Q4 25-26': {
            attendance: [
                { date: '2026-04-05', sanctuary: 1280, sumner: 1650, yh: 1298, note: 'Easter Sunday' },
                { date: '2026-04-12', sanctuary: 621, sumner: 700, yh: 610 },
                { date: '2026-04-19', sanctuary: 705, sumner: 858, yh: 608 },
                { date: '2026-04-26', sanctuary: 644, sumner: 817, yh: 549 },
                { date: '2026-05-03', sanctuary: 480, sumner: 569, yh: 680 },
                { date: '2026-05-10', sanctuary: 790, sumner: 838, yh: 658 },
                { date: '2026-05-17', sanctuary: 544, sumner: 763, yh: 662 },
                { date: '2026-05-24', sanctuary: 547, sumner: 587, yh: 571 },
                { date: '2026-05-31', sanctuary: 583, sumner: 771, yh: 596 },
                { date: '2026-06-07', sanctuary: 594, sumner: 0, yh: 604 },
                { date: '2026-06-14', sanctuary: 629, sumner: 700, yh: 584 },
                { date: '2026-06-21', sanctuary: 635, sumner: 817, yh: 591 },
                { date: '2026-06-28', sanctuary: 512, sumner: 1042, yh: 574 }
            ],
            streaming: [
                { date: '2026-04-02', label: 'Maundy Thursday', sanctuary: 1324, sumner: 1583, yh: 756 },
                { date: '2026-04-03', label: 'Good Friday', sanctuary: 1868, sumner: 3563, yh: 1635 },
                { date: '2026-04-05', label: 'Easter Sunday', sanctuary: 6032, sumner: 7380, yh: 3265 },
                { date: '2026-04-12', sanctuary: 3953, sumner: 6436, yh: 2434 },
                { date: '2026-04-19', sanctuary: 4334, sumner: 6811, yh: 2656 },
                { date: '2026-04-26', sanctuary: 4886, sumner: 5683, yh: 2764 },
                { date: '2026-05-03', sanctuary: 5379, sumner: 6940, yh: 2900 },
                { date: '2026-05-10', sanctuary: 4052, sumner: 4817, yh: 2141 },
                { date: '2026-05-17', sanctuary: 4393, sumner: 4057, yh: 12389 },
                { date: '2026-05-24', sanctuary: 4987, sumner: 3583, yh: 2216 },
                { date: '2026-05-31', sanctuary: 4717, sumner: 5254, yh: 3377 },
                { date: '2026-06-07', sanctuary: 4324, sumner: 5930, yh: 2808 },
                { date: '2026-06-14', sanctuary: 5069, sumner: 6920, yh: 3225 },
                { date: '2026-06-21', sanctuary: 5056, sumner: 7137, yh: 3240 },
                { date: '2026-06-28', sanctuary: 4082, sumner: 9648, yh: 2704 }
            ]
        },
        'Q1 26-27': {
            attendance: [
                { date: '2026-07-05', sanctuary: 460, sumner: 416, yh: 445 },
                { date: '2026-07-12', sanctuary: 558, sumner: 587, yh: 655 },
                { date: '2026-07-19', sanctuary: 591, sumner: 688, yh: 566 },
                { date: '2026-07-26', sanctuary: 563, sumner: 632, yh: 637 },
                { date: '2026-08-02', sanctuary: 614, sumner: 642, yh: 662 },
                { date: '2026-08-09', sanctuary: 667, sumner: 660, yh: 776 },
                { date: '2026-08-16', sanctuary: 651, sumner: 777, yh: 665 },
                { date: '2026-08-23', sanctuary: 710, sumner: 741, yh: 714 },
                { date: '2026-08-30', sanctuary: 672, sumner: 702, yh: 703 },
                { date: '2026-09-06', sanctuary: 600, sumner: 642, yh: 658 },
                { date: '2026-09-13', sanctuary: 718, sumner: 643, yh: 595 },
                { date: '2026-09-20', sanctuary: 606, sumner: 726, yh: 655 },
                { date: '2026-09-27', sanctuary: 623, sumner: 728, yh: 649 }
            ],
            streaming: [
                { date: '2026-07-05', sanctuary: 4489, sumner: 5008, yh: 2977 },
                { date: '2026-07-12', sanctuary: 4349, sumner: 4941, yh: 2953 },
                { date: '2026-07-19', sanctuary: 4135, sumner: 6123, yh: 3023 },
                { date: '2026-07-26', sanctuary: 5093, sumner: 3939, yh: 3063 },
                { date: '2026-08-02', sanctuary: 4037, sumner: 14463, yh: 2512 },
                { date: '2026-08-09', sanctuary: 4319, sumner: 5247, yh: 2928 },
                { date: '2026-08-16', sanctuary: 5112, sumner: 6476, yh: 3365 },
                { date: '2026-08-23', sanctuary: 4628, sumner: 4760, yh: 2595 },
                { date: '2026-08-30', sanctuary: 4568, sumner: 6090, yh: 3226 },
                { date: '2026-09-06', sanctuary: 4199, sumner: 5840, yh: 2725 },
                { date: '2026-09-13', sanctuary: 4739, sumner: 4708, yh: 3269 },
                { date: '2026-09-20', sanctuary: 4841, sumner: 5279, yh: 2920 },
                { date: '2026-09-27', sanctuary: 4722, sumner: 4243, yh: 2958 }
            ]
        },
        'Q2 26-27': {
            attendance: [
                { date: '2026-10-04', sanctuary: 757, sumner: 785, yh: 0 }
            ],
            streaming: [
                { date: '2026-10-04', sanctuary: 4308, sumner: 3126, yh: 3166 }
            ]
        }
    }
};
